import Head from 'next/head'
import Button from '@material-ui/core/Button'
import styles from '../styles/index.module.scss'

export default function Home() {
  return (
    <div className={styles.bg}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button variant="contained" color="primary">
          Hello World
        </Button>
      </main>
    </div>
  );
}
